class Job < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択してください' },
    { id: 2, name: '会社員' },
    { id: 3, name: '公務員' },
    { id: 4, name: '医師' },
    { id: 5, name: '弁護士' },
    { id: 6, name: '公認会計士' },
    { id: 7, name: '税理士' },
    { id: 8, name: '建築士' },
    { id: 9, name: '教師' },
    { id: 10, name: '歯科医師' },
    { id: 11, name: '歯科衛生士' },
    { id: 12, name: '経営者・役員' },
    { id: 13, name: '大学教員・教授' },
    { id: 14, name: '芸能・モデル' },
    { id: 15, name: 'クリエイター' },
    { id: 16, name: 'デザイナー' },
    { id: 17, name: 'エンジニア' },
    { id: 18, name: 'パイロット' },
    { id: 19, name: '客室乗務員' },
    { id: 20, name: 'アパレル' },
    { id: 21, name: 'アナウンサー' },
    { id: 22, name: '秘書' },
    { id: 23, name: '看護師' },
    { id: 24, name: '保育士' },
    { id: 25, name: '調理師・栄養士' },
    { id: 26, name: '美容師' },
    { id: 27, name: '薬剤師' },
    { id: 28, name: '通訳・翻訳者' },
    { id: 29, name: 'スポーツ選手' },
    { id: 30, name: '接客業' },
    { id: 31, name: 'イベント関連' },
    { id: 32, name: '介護・福祉' },
    { id: 33, name: 'ブライダル' },
    { id: 34, name: '広告・マスコミ' },
    { id: 35, name: '学生' },
    { id: 36, name: 'フリーランス' },
    { id: 37, name: '個人事業主' },
    { id: 38, name: 'パート・アルバイト' },
    { id: 39, name: '主婦・主夫' },
    { id: 40, name: 'その他' },
  ]
  include ActiveHash::Associations
  has_many :users
end